# Generated by Django 3.1.6 on 2021-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210220_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(choices=[(100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400')]),
        ),
    ]
