# Generated by Django 3.1.6 on 2021-03-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='categories',
        ),
    ]
