# Generated by Django 3.1.7 on 2021-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210330_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='article-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(default='Sub title', max_length=300),
            preserve_default=False,
        ),
    ]
