# Generated by Django 3.2 on 2021-08-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='banner_image',
            field=models.ImageField(default='banner_image/1.jpg', upload_to='banner_image/'),
            preserve_default=False,
        ),
    ]
