# Generated by Django 3.2 on 2021-08-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configuration_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='banner_prefix_text',
            field=models.CharField(default='Welcome to', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='banner_subtitle',
            field=models.CharField(default='The home of countless innovations', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='banner_title',
            field=models.CharField(default='ACES, KNUST', max_length=40),
            preserve_default=False,
        ),
    ]
