# Generated by Django 3.2 on 2021-08-03 01:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210802_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='mission',
            field=ckeditor.fields.RichTextField(default='Mission statement'),
            preserve_default=False,
        ),
    ]
