"""
Django settings for aces_web project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY = (str, "*y11u$y5r%5b7st+i&$wxyujse5th(7y5x16l63kqzw6w4&b%v"),
    ALLOWED_HOSTS = (list, ['*']),
    DB_PORT = (int, 3306),
    DB_HOST= (str, 'localhost'),
    EMAIL_PORT = (int, 587),
    EMAIL_USE_TLS = (bool, True),
    MEDIA_ROOT = (str, BASE_DIR / "media")
)
try:
    environ.Env.read_env(open(BASE_DIR/'.env'))
except:
    pass
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS')

INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    # custom apps

    'accounts.apps.AccountsConfig',
    'core.apps.CoreConfig',

    # django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django.contrib.sitemaps',

    # Third party
    'whitenoise.runserver_nostatic',
    'crispy_forms',
    'debug_toolbar',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # third party
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'aces_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aces_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        },
    }
else:
    DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.mysql",
            'NAME': env('DB_NAME'),
            'USER': env('DB_USERNAME'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT'),
            "OPTIONS": {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
                'use_unicode': True,
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "static"
MEDIA_URL = "/media/"
MEDIA_ROOT = env('MEDIA_ROOT')
CRISPY_TEMPLATE_PACK = "bootstrap4"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# login logout redirects
LOGIN_REDIRECT_URL = "accounts:login_success"
LOGOUT_REDIRECT_URL = "/"

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
USE_L10N = False

ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 12400

# SESSION DURATION
# SESSION_COOKIE_AGE = 60 * 60 # 1 HOUR
# Custom user model
AUTH_USER_MODEL = "accounts.CustomUser"



# email settings
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env("EMAIL_HOST")
    EMAIL_PORT = env("EMAIL_PORT")
    EMAIL_HOST_USER = env("EMAIL_HOST_USER")
    EMAIL_USE_TLS = env("EMAIL_USE_TLS")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# MaximumTime since last seen to consider a user as online in seconds
# USER_ONLINE_TIMEOUT = 5*60 # 5 minutes


# Easy_thumbnail settings
THUMBNAIL_ALIASES = {
    '': {
        'nocrop': {'quality': 1},
        'avatar': {'size': (50, 50), 'crop': "smart"},
        'avatar70': {'size': (70, 70), 'crop': "smart"},
        'avatar80': {'size': (80, 80), 'crop': "smart"},
        'avatar100': {'size': (100, 100), 'crop': "smart"},
        'avatar160': {'size': (160, 160), 'crop': 'smart'},
        'card': {'size': (250, 150), 'crop': "smart"},
        'cardlarge': {'size': (350, 250), 'crop': 'smart'},
        'cardsmall': {'size': (160, 110), 'crop': "smart"},
    },
}